feat: add footer graphics
climatEDU/climatEDU pull request #30
Opened 2020-08-29 06:51 UTC by DarinMao

this is currently extremely hacky, do not merge

there's gotta be a nicer way to implement this?

2020-08-29 18:14 UTC, DarinMao commented
I've instead cropped the bottom edge of the image and placed a box under it. The color in the image is very close to primary but not quite, so I've set the background color of the box to match (`#007439`). 

In order to keep padding between content and footer consistent I've put this in the layout, but this means some extra nesting to keep the padding background color correct. 

Should we perhaps serve a smaller image to small screens? A 2000px image is unlikely to be useful.

Currently the background color is passed via `backgroundColor` prop so that the landing page looks correct. Any ideas for a less stupid approach?

I've observed some issues with pixel rounding putting borders between the image and the rest of the footer. Can someone investigate?

Social links are now in site metadata, @vivieli77 change the links some time please

2020-08-29 18:36 UTC, joshdabosh commented
bruh change the socials LOL

2020-08-29 18:37 UTC, joshdabosh commented on gatsby-config.js
> +        href: 'https://youtube.com/watch?v=dQw4w9WgXcQ',
change

2020-08-30 00:11 UTC, DarinMao commented on src/gatsby-plugin-theme-ui/index.js
> +    footer: '400px',
remove

2020-08-30 21:13 UTC, DarinMao commented
may want to adjust sharp settings

2020-09-02 20:32 UTC, ethanwu10 requested changes
The main issue I see right now is the PR breaking scrollbar styles; we may want to figure out if we can style the `html` element as the scroll root, but I'm not sure if we are able to create global styles with theme-ui.

Also, we may want to consider having the footer image be a constant height and get cropped horizontally to fit the viewport.

2020-09-02 20:32 UTC, ethanwu10 commented on src/gatsby-plugin-theme-ui/index.js
> +      minHeight: '100vh',
This breaks scrollbar styles, since the `root` element is no longer the scroll root.

2020-09-02 20:32 UTC, ethanwu10 commented on src/components/layout.js
> +const Layout = ({ children, backgroundColor }) => {
Prefer `bg` instead of `backgroundColor` for consistency with theme-ui.

2020-09-02 20:32 UTC, ethanwu10 commented on src/components/layout.js
> +          backgroundColor: backgroundColor,
```suggestion
          bg: backgroundColor,
```

2020-09-02 20:32 UTC, ethanwu10 commented on src/components/layout.js
> +            backgroundColor: backgroundColor,
```suggestion
            bg: backgroundColor,
```

2020-09-02 20:32 UTC, ethanwu10 commented on src/components/layout.js
> +      <Flex
Consider pulling the footer out into a separate component.

2020-09-02 20:32 UTC, ethanwu10 commented on src/components/layout.js
> +        sx={{
```suggestion
        as='main'
        sx={{
```

2020-09-09 02:41 UTC, ethanwu10 approved these changes
lgtm, though footer could still be pulled out into a separate component.

2020-09-09 03:39 UTC, DarinMao commented
lmao no

2020-09-09 03:39 UTC, DarinMao commented
lmao no

2020-09-09 14:09 UTC, vivieli77 submitted a review, later dismissed
yesss

2020-09-09 22:28 UTC, joshdabosh approved these changes

2020-09-09 22:28 UTC, merged